### ISSUE TITLE
NaN in stepwise mutation matrix

### ISSUE THREAD

**Issue by magnusdv** [magnusdv/pedmut#5]
@thoree this came up as I'm adding unit tests for the stepwise model. 
Can you suggest a code change to avoid these NaN's?

``` r
pedmut::mutationMatrix(alleles = 1:3, model = "step", rate=0, rate2=0, range=0)
#>     1   2   3
#> 1   1 NaN NaN
#> 2 NaN   1 NaN
#> 3 NaN NaN   1
#> 
#> Model: stepwise 
#> Rate: 0 
#> range:  0 
#> rate2:  0 
#> 
#> Lumpable: Always
```

<sup>Created on 2018-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thoree** [comment]
I have corrected and pushed the checking of the `range` parameter; 0 is no longer a legal value:
``` r
pedmut::mutationMatrix(alleles = 1:3, model = "step", rate=0, rate2=0, range=0)
#> Error: `range` must be a positive number: 0
```

<sup>Created on 2018-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Thanks, fixed now.
